version: "3.9"
   
services:
  web:
    container_name: cv_generator
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    restart: always
    volumes:
      - .:/code
    ports:
      - "5000:5000"
